name: gtads_bqt
description: GTAds百青藤广告支持
version: 1.0.1
homepage: https://github.com/gstory0404/GTAds/blob/master/gtads_bqt

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  gtads: ^0.0.6
  baiduad: ^0.0.4
#  baiduad:
#    git:
#      url: https://github.com/gstory0404/baiduad.git
#      ref: 8596f7c01998e91c3c4ca6da4b4bbd80826c8db5

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.gstory.gtads_bqt
        pluginClass: GtadsBqtPlugin
      ios:
        pluginClass: GtadsBqtPlugin
