name: gtads_example
description: Demonstrates how to use the gtads plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

#  gtads: ^1.5.0
#  gtads:
#    path: ../
  # 穿山甲
  gtads_csj:
    path: ../../gtads_csj
  # 优量汇y
  gtads_ylh:
    path: ../../gtads_ylh
  # Sigmob
  gtads_sigmob:
    path: ../../gtads_sigmob
  # 百青藤
  gtads_bqt:
    path: ../../gtads_bqt

#  gtads: ^1.3.0
#  #字节穿山甲广告
#  gtads_csj: ^1.3.0
#  #腾讯优量汇广告
#  gtads_ylh: ^1.3.1
#  #优量汇广告
#  gtads_sigmob: ^1.3.0
#  #百度百青藤广告
#  gtads_bqt: ^1.3.1

override_dependencies:
  gtads:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

