name: gtads_sigmob_example
description: Demonstrates how to use the gtads_sigmob plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  gtads_sigmob:
    path: ../

  cupertino_icons: ^1.0.2
  gtads: ^0.0.6
#  gtads:
#    path: ../../gtads

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
