name: gtads_csj_example
description: Demonstrates how to use the gtads_csj plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  gtads_csj:
    path: ../
#  gtads_csj:
#    git:
#      url: https://github.com/gstory0404/GTAds.git
#      path: gtads_csj/

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
