name: gtads_csj
description: GTAds-穿山甲广告支持
version: 1.2.3
homepage: https://github.com/gstory0404/GTAds/blob/master/gtads_csj

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_unionad: ^1.3.21
  gtads: ^1.2.0
#  gtads:
#    path: ../gtads
  

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.gtads_csj
        pluginClass: GtadsCsjPlugin
      ios:
        pluginClass: GtadsCsjPlugin